import React from 'react';

/**
 * DevLinkProvider manages Webflow interactions in your project
 * This will be generated by DevLink when you sync with your Webflow site
 */

export const DevLinkProvider = ({ children }) => {
  React.useEffect(() => {
    // Initialize Webflow interactions
    if (typeof window !== 'undefined' && window.Webflow) {
      window.Webflow.destroy();
      window.Webflow.ready();
      window.Webflow.require('ix2').init();
    }
  }, []);

  return <>{children}</>;
};

