import React from 'react';

/**
 * Basic Webflow components for building layouts
 * These will be generated by DevLink when you sync with your Webflow site
 */

export const Section = ({ children, className = '', tag: Tag = 'section', style = {}, ...props }) => {
  return (
    <Tag className={className} style={style} {...props}>
      {children}
    </Tag>
  );
};

export const Container = ({ children, className = '', tag: Tag = 'div', ...props }) => {
  return (
    <Tag className={`container ${className}`} {...props}>
      {children}
    </Tag>
  );
};

export const Block = ({ children, className = '', tag: Tag = 'div', style = {}, ...props }) => {
  return (
    <Tag className={className} style={style} {...props}>
      {children}
    </Tag>
  );
};

export const Link = ({ 
  children, 
  className = '', 
  button = false, 
  options = {}, 
  ...props 
}) => {
  const Tag = options.href ? 'a' : 'button';
  return (
    <Tag 
      className={`${button ? 'button ' : ''}${className}`} 
      {...options}
      {...props}
    >
      {children}
    </Tag>
  );
};

export const Heading = ({ children, className = '', tag: Tag = 'h1', ...props }) => {
  return (
    <Tag className={className} {...props}>
      {children}
    </Tag>
  );
};

export const Paragraph = ({ children, className = '', ...props }) => {
  return (
    <p className={className} {...props}>
      {children}
    </p>
  );
};

